// <auto-generated />
using System;
using HayvanBakımıDb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HayvanBakımıDb.Migrations
{
    [DbContext(typeof(HayvanBakımDb))]
    partial class HayvanBakımDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HayvanBakımıDb.Models.Bakici", b =>
                {
                    b.Property<int>("BakiciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BakiciId"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BakiciId");

                    b.ToTable("Bakicilar");
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Hayvan", b =>
                {
                    b.Property<int>("HayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HayID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Agirlik")
                        .HasColumnType("float")
                        .HasColumnName("Kilo");

                    b.Property<int>("BakId")
                        .HasColumnType("int");

                    b.Property<string>("Cins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SahibiVarMi")
                        .HasColumnType("bit");

                    b.Property<int>("SahipId")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HayID");

                    b.HasIndex("BakId");

                    b.HasIndex("SahipId");

                    b.ToTable("Hayvanlar");
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Sahip", b =>
                {
                    b.Property<int>("SahipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SahipID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SahipID");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Yiyecek", b =>
                {
                    b.Property<int>("YiyecekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YiyecekID"), 1L, 1);

                    b.Property<decimal>("Kalori")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YiyecekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YiyecekIcerigi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YiyecekID");

                    b.ToTable("Yiyecekler");
                });

            modelBuilder.Entity("HayvanYiyecek", b =>
                {
                    b.Property<int>("HayvanlarHayID")
                        .HasColumnType("int");

                    b.Property<int>("YiyeceklerYiyecekID")
                        .HasColumnType("int");

                    b.HasKey("HayvanlarHayID", "YiyeceklerYiyecekID");

                    b.HasIndex("YiyeceklerYiyecekID");

                    b.ToTable("HayvanYiyecek");
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Hayvan", b =>
                {
                    b.HasOne("HayvanBakımıDb.Models.Bakici", "Bakici")
                        .WithMany("Hayvanlar")
                        .HasForeignKey("BakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HayvanBakımıDb.Models.Sahip", "Sahip")
                        .WithMany("Hayvanlar")
                        .HasForeignKey("SahipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bakici");

                    b.Navigation("Sahip");
                });

            modelBuilder.Entity("HayvanYiyecek", b =>
                {
                    b.HasOne("HayvanBakımıDb.Models.Hayvan", null)
                        .WithMany()
                        .HasForeignKey("HayvanlarHayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HayvanBakımıDb.Models.Yiyecek", null)
                        .WithMany()
                        .HasForeignKey("YiyeceklerYiyecekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Bakici", b =>
                {
                    b.Navigation("Hayvanlar");
                });

            modelBuilder.Entity("HayvanBakımıDb.Models.Sahip", b =>
                {
                    b.Navigation("Hayvanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
